In [106]:
import pandas as pd
import requests
from pandas.io.json import json_normalize
import numpy as np
from sqlalchemy import create_engine

Get the schedule Data for Vancouver

In [94]:
url = 'http://data.streetfoodapp.com/1.1/schedule/vancouver'
data =  requests.get(url).json()
data2 = pd.DataFrame.from_dict(data)
data3 = data2["vendors"].apply(pd.Series)
data3.head()

,0,catering,delivery_url,description,description_short,email,facebook,identifier,images,instagram,...,open_updated,payment_methods,phone,promoted,rank,rating,region,takeout_url,twitter,url
ads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
new,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
arturos-to-go,NaN,None,None,Arturo's unique recipes are a fusion of Spanis...,"Authentic, author gourmet Mexican made with th...",info@arturos2go.com,arturosmexico2go,arturos-to-go,{'logo': 'https://cdn.streetfoodapp.com/images...,arturos2go,...,1.633977e+09,"[cash, credit_card, debit_card, apple_pay]",(604) 202-4043,True,8.0,1644.0,vancouver,None,arturomexico2go,arturos2go.com
babas-house,NaN,None,None,Baba's House specialize in Old Fashion Homemad...,None,maggierabek@yahoo.com,None,babas-house,NaN,babashousekitchen,...,NaN,"[cash, credit_card, debit_card, apple_pay]",(778) 838-5059,False,113.0,15.0,vancouver,None,BabasHouse2,babashousekitchen.com

In [95]:
data4 = data3[['description', 'name', 'description_short', 'last']].copy()
data4 = data4.dropna()
data4.head()

,description,name,description_short,last
arturos-to-go,Arturo's unique recipes are a fusion of Spanis...,arturosmexico2go,"Authentic, author gourmet Mexican made with th...","{'time': 1633635000, 'display': 'Howe St & W C..."
bc-taco,"Handmade, always fresh. Tacos, burritos, quesa...",BC TACO,"Handmade, always fresh. Tacos, burritos, quesa...","{'time': 1633635000, 'display': 'Rocky Point S..."
beavertails,Deliciously famous Canadian pastry. Proudly sa...,BeaverTails Mobile (Vancouver),Deliciously famous Canadian pastry. Proudly sa...,"{'time': 1632708000, 'display': 'Richmond Nigh..."
boca-o,"BOCA'O is the abbreviation of BOCADO, or BITE ...",Boca'o Spain in a bite,Boca'O uses premium Spanish and local ingredie...,"{'time': 1633629600, 'display': 'Jonathan Roge..."
burgerholic,BurgerHolic in Vancouver is specializes in mou...,BurgerHolic,Happy to cater your next event Burgerholic.ca@...,"{'time': 1633629600, 'display': 'Jonathan Roge..."

In [96]:
Vandata = data4["last"].apply(pd.Series)
Vandata.insert(4, "Location", "Vancouver")
Vandata.head()

,time,display,latitude,longitude,Location
arturos-to-go,1633635000,Howe St & W Cordova St,49.286466,-123.113481,Vancouver
bc-taco,1633635000,"Rocky Point Spirits - 2805 Murray St, Port Moody",49.278868,-122.849935,Vancouver
beavertails,1632708000,"Richmond Night Market, 8351 River Rd, Richmond...",49.192471,-123.133009,Vancouver
boca-o,1633629600,"Jonathan Rogers Park, W 8th Ave, Vancouver",49.263825,-123.108102,Vancouver
burgerholic,1633629600,Jonathan Rogers Park,49.264289,-123.107978,Vancouver

Grab Boston

In [97]:
url = 'http://data.streetfoodapp.com/1.1/schedule/boston'
data =  requests.get(url).json()
data2 = pd.DataFrame.from_dict(data)
data3 = data2["vendors"].apply(pd.Series)
data3.head()

,0,catering,delivery_url,description,description_short,email,facebook,identifier,images,instagram,...,open_updated,payment_methods,phone,promoted,rank,rating,region,takeout_url,twitter,url
ads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
new,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
bon-me,NaN,None,None,"Bold, Fresh, and Fun Asian cuisine.",None,info@bonmetruck.com,None,bon-me,NaN,None,...,NaN,"[cash, credit_card, debit_card]",(617) 989-9804,False,3.0,893.0,boston,None,bonme,bonmetruck.com
bon-me-10,NaN,"{'guest_paid_enabled': False, 'host_paid_enabl...",None,"Bold, Fresh, and Fun Asian cuisine.",None,info@bonmetruck.com,None,bon-me-10,NaN,None,...,NaN,"[cash, credit_card, debit_card]",(617) 989-9804,False,61.0,6.0,boston,None,bonme,bonmetruck.com

In [67]:
data4 = data3[['description', 'name', 'description_short', 'last']].copy()
data4 = data4.dropna()
data4.head()

,description,name,description_short,last
arturos-to-go,Arturo's unique recipes are a fusion of Spanis...,arturosmexico2go,"Authentic, author gourmet Mexican made with th...","{'time': 1633635000, 'display': 'Howe St & W C..."
bc-taco,"Handmade, always fresh. Tacos, burritos, quesa...",BC TACO,"Handmade, always fresh. Tacos, burritos, quesa...","{'time': 1633635000, 'display': 'Rocky Point S..."
beavertails,Deliciously famous Canadian pastry. Proudly sa...,BeaverTails Mobile (Vancouver),Deliciously famous Canadian pastry. Proudly sa...,"{'time': 1632708000, 'display': 'Richmond Nigh..."
boca-o,"BOCA'O is the abbreviation of BOCADO, or BITE ...",Boca'o Spain in a bite,Boca'O uses premium Spanish and local ingredie...,"{'time': 1633629600, 'display': 'Jonathan Roge..."
burgerholic,BurgerHolic in Vancouver is specializes in mou...,BurgerHolic,Happy to cater your next event Burgerholic.ca@...,"{'time': 1633629600, 'display': 'Jonathan Roge..."

In [99]:
BosData = data4["last"].apply(pd.Series)
BosData.insert(4, "Location", "Boston")
BosData.head()

,time,display,latitude,longitude,Location
arturos-to-go,1633635000,Howe St & W Cordova St,49.286466,-123.113481,Boston
bc-taco,1633635000,"Rocky Point Spirits - 2805 Murray St, Port Moody",49.278868,-122.849935,Boston
beavertails,1632708000,"Richmond Night Market, 8351 River Rd, Richmond...",49.192471,-123.133009,Boston
boca-o,1633629600,"Jonathan Rogers Park, W 8th Ave, Vancouver",49.263825,-123.108102,Boston
burgerholic,1633629600,Jonathan Rogers Park,49.264289,-123.107978,Boston

Get the Tallahassee Data

In [102]:
url = 'http://data.streetfoodapp.com/1.1/schedule/tallahassee'
data =  requests.get(url).json()
data2 = pd.DataFrame.from_dict(data)
data3 = data2["vendors"].apply(pd.Series)
data3.head()

,0,catering,delivery_url,description,description_short,email,facebook,identifier,images,instagram,...,open_updated,payment_methods,phone,promoted,rank,rating,region,takeout_url,twitter,url
ads,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
new,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
regions,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
big-easy-snowballs,NaN,NaN,NaN,Serving Traditional New Orleans Style snowball...,Traditional New Orleans style snowballs,john@bigeasysnowballs.com,None,big-easy-snowballs,{'logo': 'https://cdn.streetfoodapp.com/images...,None,...,NaN,None,(850) 329-6010,True,8.0,69.0,tallahassee,None,snowballstally,bigeasysnowballs.com
el-criollo,NaN,NaN,NaN,Authentic homemade Puerto Rican Cuisine.,Authentic homemade Puerto Rican Cuisine.,artcuisine66@gmail.com,None,el-criollo,{'logo': 'https://cdn.streetfoodapp.com/images...,None,...,1.633705e+09,"[cash, credit_card, debit_card, apple_pay]",(850) 322-2328,True,1.0,427.0,tallahassee,None,elcriollogrill,elcriollogrill.com

In [103]:
data4 = data3[['description', 'name', 'description_short', 'last']].copy()
data4 = data4.dropna()
data4.head()

,description,name,description_short,last
big-easy-snowballs,Serving Traditional New Orleans Style snowball...,Big Easy Snowballs,Traditional New Orleans style snowballs,"{'time': 1537624800, 'display': 'Tallahassee N..."
el-criollo,Authentic homemade Puerto Rican Cuisine.,El Criollo Grill,Authentic homemade Puerto Rican Cuisine.,"{'time': 1633618800, 'display': 'Innovation Pa..."
fired-up-pizza,We bake our flatbread pizzas with using fresh ...,Fired Up Pizza,flatbread and gluten free pizza.,"{'time': 1619127000, 'display': 'Tekesta Park,..."
julios-food-on-the-move,Julio's Food On The Move is a Puerto Rican/Ame...,Julio's Food on the Move,Puerto Rican and American food,"{'time': 1633123800, 'display': 'First Friday ..."
king-kuisine,"We are challenging the city's residents to ""TR...",King Kuisine,Trust your gut and come experience our clever ...,"{'time': 1584133200, 'display': 'Lake Tribe Br..."

In [111]:
TalData = data4["last"].apply(pd.Series)
TalData.insert(4, "Location", "Boston")
TalData.head()

,time,display,latitude,longitude,Location
big-easy-snowballs,1537624800,Tallahassee Nurseries,30.482244,-84.256475,Boston
el-criollo,1633618800,Innovation Park (2031 E. Paul Dirac Dr),30.423553,-84.320257,Boston
fired-up-pizza,1619127000,"Tekesta Park, 8241 Bridge Water Trail, Tallaha...",30.582247,-84.236763,Boston
julios-food-on-the-move,1633123800,"First Friday at Railroad Square, 618 McDonnell...",30.432946,-84.291657,Boston
king-kuisine,1584133200,"Lake Tribe Brewing Company, 3357 Garber Dr #4,...",30.465836,-84.352503,Boston

In [112]:
merged_df  = pd.concat([Bosdata,TalData, Vandata])
merged_df =  merged_df.reset_index()
merged_df.head()

,index,time,display,latitude,longitude,Location
0,arturos-to-go,1633635000,Howe St & W Cordova St,49.286466,-123.113481,Boston
1,bc-taco,1633635000,"Rocky Point Spirits - 2805 Murray St, Port Moody",49.278868,-122.849935,Boston
2,beavertails,1632708000,"Richmond Night Market, 8351 River Rd, Richmond...",49.192471,-123.133009,Boston
3,boca-o,1633629600,"Jonathan Rogers Park, W 8th Ave, Vancouver",49.263825,-123.108102,Boston
4,burgerholic,1633629600,Jonathan Rogers Park,49.264289,-123.107978,Boston

In [113]:
merged_df.columns = ['Foodtruck', 'Time', 'Display_name', 'Lat', 'Long', 'Location']
merged_df.head()

,Foodtruck,Time,Display_name,Lat,Long,Location
0,arturos-to-go,1633635000,Howe St & W Cordova St,49.286466,-123.113481,Boston
1,bc-taco,1633635000,"Rocky Point Spirits - 2805 Murray St, Port Moody",49.278868,-122.849935,Boston
2,beavertails,1632708000,"Richmond Night Market, 8351 River Rd, Richmond...",49.192471,-123.133009,Boston
3,boca-o,1633629600,"Jonathan Rogers Park, W 8th Ave, Vancouver",49.263825,-123.108102,Boston
4,burgerholic,1633629600,Jonathan Rogers Park,49.264289,-123.107978,Boston

In [114]:
rds_connection_string = "postgres:postgres@localhost:5432/FoodTruck_db"
engine = create_engine(f'postgresql://{rds_connection_string}')

In [116]:
merged_df.to_sql(name='citydata', con=engine, if_exists='replace', index=False)